### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ssahibsingh** [ggeeks/website_games#4]
Add new Games to Readme

**Comment by MoNakouzi** [comment]
@ssahibsingh If this issue is still available, can you assign it to me?

**Comment by ssahibsingh** [comment]
Sure. Go Ahead @MoNakouzi

**Comment by MoNakouzi** [comment]
Thank you. Just to confirm I should add the links of the two other games to the readme file, correct? Would you also like me to add a brief description of each or something additional?

**Comment by ssahibsingh** [comment]
Yes, You have to add the links of the other games and also you can add description about each game.

**Comment by MoNakouzi** [comment]
@ssahibsingh Sorry if this is a bad question, but where can I find the links of the games that I will be adding to the README file?

**Comment by ssahibsingh** [comment]
It is totally fine @MoNakouzi.

Link for each game will be of the format: 

> `https://gaminggeeks.online/website_games/<Game Folder Name>`

Example: 

Pong Game
Folder Name: pong
Link: [https://gaminggeeks.online/website_games/pong](https://gaminggeeks.online/website_games/pong)

**Comment by MoNakouzi** [comment]
Got it, thank you!
